#cloud-config
hostname: carolinabarbosa.com
fqdn: carolinabarbosa.com
timezone: UTC

package_update: true
package_upgrade: true

packages:
  - ufw
  - fail2ban
  - apache2
  - mysql-server
  - php
  - php-mysql
  - libapache2-mod-php
  - php-cli
  - php-curl
  - php-gd
  - php-mbstring
  - php-xml
  - php-xmlrpc
  - php-soap
  - php-intl
  - php-zip
  - wget
  - unzip
  - certbot
  - python3-certbot-apache

users:
  - default

write_files:
  - path: /etc/fail2ban/jail.d/ssh.conf
    content: |
      [sshd]
      enabled = true
      port    = ssh
      logpath = %(sshd_log)s
      maxretry = 5
      bantime = 3600
      findtime = 600

  - path: /etc/fail2ban/jail.d/apache-wordpress.conf
    content: |
      [apache-wordpress]
      enabled = true
      port = http,https
      filter = apache-wordpress
      logpath = /var/log/apache2/access.log
      maxretry = 5
      bantime = 3600
      findtime = 600

  - path: /etc/fail2ban/filter.d/apache-wordpress.conf
    content: |
      [Definition]
      failregex = <HOST> -.*"(GET|POST).*xmlrpc\.php.*
      ignoreregex =

runcmd:

  # Download and install WordPress
  - wget https://wordpress.org/latest.zip -P /tmp
  - unzip /tmp/latest.zip -d /var/www/
  - cp /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php
  - sed -i "s/database_name_here/wordpress/" /var/www/wordpress/wp-config.php
  - sed -i "s/username_here/wpuser/" /var/www/wordpress/wp-config.php
  - sed -i "s/password_here/changeme/" /var/www/wordpress/wp-config.php
  - echo "define('WP_AUTO_UPDATE_CORE', true);" >> /var/www/wordpress/wp-config.php

  # Set permissions
  - chown -R www-data:www-data /var/www/wordpress
  - chmod -R 755 /var/www/wordpress

  # Remove default Apache site
  - a2dissite 000-default.conf || true
  - a2dissite default-ssl.conf || true
  - rm -rf /etc/apache2/sites-available/000-default.conf
  - rm -rf /etc/apache2/sites-available/default-ssl.conf
  - systemctl reload apache2

write_files:

  # Disable XML-RPC
  - path: /var/www/wordpress/.htaccess
    content: |
      <Files xmlrpc.php>
        Order Deny,Allow
        Deny from all
      </Files>
  - path: /etc/apache2/sites-available/wordpress.conf
    content: |
      <VirtualHost *:80>
          ServerName carolinabarbosa.com
          ServerAlias www.carolinabarbosa.com carolinabarbosa.com.br www.carolinabarbosa.com.br
  
          RewriteEngine On
          RewriteCond %{HTTP_HOST} !^carolinabarbosa\\.com$ [NC]
          RewriteRule ^ https://carolinabarbosa.com%{REQUEST_URI} [L,R=301]
  
          ErrorLog ${APACHE_LOG_DIR}/error.log
          CustomLog ${APACHE_LOG_DIR}/access.log combined
      </VirtualHost>
  
      <IfModule mod_ssl.c>
      <VirtualHost *:443>
          ServerName carolinabarbosa.com
          ServerAlias www.carolinabarbosa.com carolinabarbosa.com.br www.carolinabarbosa.com.br
          DocumentRoot /var/www/wordpress
  
          <Directory /var/www/wordpress>
              Options -Indexes
              AllowOverride All
          </Directory>
  
          Header always set X-Content-Type-Options "nosniff"
          Header always set X-Frame-Options "SAMEORIGIN"
          Header always set X-XSS-Protection "1; mode=block"
  
          ErrorLog ${APACHE_LOG_DIR}/error_ssl.log
          CustomLog ${APACHE_LOG_DIR}/access_ssl.log combined
      </VirtualHost>
      </IfModule>

runcmd:
  - a2ensite wordpress
  - a2enmod rewrite headers ssl
  - systemctl reload apache2

  # Request Let's Encrypt certificates for all domains
  - certbot --apache --non-interactive --agree-tos --redirect --email admin@carolinabarbosa.com  -d carolinabarbosa.com -d www.carolinabarbosa.com -d carolinabarbosa.com.br -d www.carolinabarbosa.com.br

  # Enable automatic certificate renewal
  - systemctl enable certbot.timer
  - systemctl start certbot.timer

  # Disable swap
  - swapoff -a
  - sed -i '/swap/d' /etc/fstab

  # Harden SSH
  - sed -i 's/^#*PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
  - systemctl restart sshd

  # Enable UFW
  - ufw allow 22
  - ufw allow 80
  - ufw allow 443
  - ufw --force enable

  # Harden MySQL
  - mysql -e "DELETE FROM mysql.user WHERE User='';"
  - mysql -e "DROP DATABASE IF EXISTS test;"
  - mysql -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';"
  - mysql -e "FLUSH PRIVILEGES;"

  # Create MySQL DB and user for WordPress
  - mysql -e "CREATE DATABASE wordpress;"
  - mysql -e "CREATE USER 'wpuser'@'localhost' IDENTIFIED BY 'changeme';"
  - mysql -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wpuser'@'localhost';"
  - mysql -e "FLUSH PRIVILEGES;"

  # Enable and configure fail2ban
  - systemctl enable fail2ban
  - systemctl restart fail2ban

final_message: |
  cloud-init has finished
  version: $version
  timestamp: $timestamp
  datasource: $datasource
  uptime: $uptime
